routes/web.php
<?php

use App\Imports\ServicesImport;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes([
    'register' => false,
    'reset' => false,
    'verify' => false
]);

Route::group(['middleware' => 'role:admin'], function () {
    Route::resource('place', 'PlaceController')->except('show');
    Route::resource('event', 'EventController')->except('show');
    Route::resource('email-banner', 'EmailBannerController')->except('show');
    Route::resource('tip', 'TipController')->except('show');
    Route::resource('service', 'ServiceController')->except('show');
    Route::resource('shop', 'ShopController')->except('show');
    Route::resource('ad', 'AdvertisingController')->except('show');
    Route::resource('user', 'UserController')->except('show');
    Route::resource('author', 'AuthorController')->except('show');
    Route::get('logout', 'Auth\AuthController@logout')->name('logout');


    Route::get('diactivate/place/{place}', 'PlaceController@diactivate')->name('place.diactivate');
    Route::get('diactivate/email-banner/{emailBanner}', 'EmailBannerController@diactivate')->name('email-banner.diactivate');
    Route::get('diactivate/event/{event}', 'EventController@diactivate')->name('event.diactivate');
    Route::get('diactivate/tip/{tip}', 'TipController@diactivate')->name('tip.diactivate');
    Route::get('diactivate/service/{service}', 'ServiceController@diactivate')->name('service.diactivate');
    Route::get('diactivate/shop/{shop}', 'ShopController@diactivate')->name('shop.diactivate');
    Route::get('diactivate/ad/{ad}', 'AdvertisingController@diactivate')->name('ad.diactivate');

    // Excel export
    Route::get('user/export', 'UserController@export')->name('user.export');
    Route::get('/excel-imports', function () {
        return view('import');
    });

    Route::post('import-data', function (Request $request) {
        Excel::import(new ServicesImport, $request->file('file'));
        return back();
    })->name('import');
});

Route::get('password/reset', 'Auth\AuthController@resetPassword')->name('reset.password');
Route::post('password/update', 'Auth\AuthController@updatePassword')->name('update.password');
Route::get('account/activate', 'Auth\AuthController@accountActivate')->name('activate.account');
Route::get('redirect/{token}', 'RedirectController@index')->name('redirect');
Route::get('/welcome', 'RedirectController@index');

Route::get('/bucket-list/{token}', 'UserController@bucketMap')->name('bucket.list');


Route::get('/welcome', function () {
    return view('welcome');
});

Route::get('home', function () {
    return view('home');
});

Route::get('/', function () {
    return redirect()->route('login');
});


Route::get('fake/users', function () {
    factory(App\User::class, 100)->create();
});

app/Author.php
<?php

namespace App;

use App\Filters\UserFilter as Filters;
use Illuminate\Database\Eloquent\Model;

class Author extends Model
{
    use  EntryFilter;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'photo',
        'name',
        'proffession_en',
        'proffession_de',
    ];

    public function tips()
    {
        return $this->hasMany(Tip::class);
    }
}

app/Http/Controllers/AuthorController.php
<?php

namespace App\Http\Controllers;

use App\Author;
use App\Filters\EntryFilter;
use App\Filters\UserFilter;
use Illuminate\Http\Request;

class AuthorController extends Controller
{
    use ImageUploader;

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(EntryFilter $filters)
    {
        $authors = Author::latest()->filter($filters)->paginate(25);

        return view('admin.author.index', compact('authors'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.author.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'photo' => 'required|mimes:jpg,jpeg|dimensions:min_width=512,min_height=512',
            'name' => 'required',
            'proffession_en' => 'required',
            'proffession_de' => 'required',
        ]);

        $photo = $this->upload($request->photo);

        Author::create([
            'photo' => $photo,
            'name' => $request->name,
            'proffession_en' => $request->proffession_en,
            'proffession_de' => $request->proffession_de
        ]);

        return redirect()->route('author.index');
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(Request $request, Author $author)
    {
        return view('admin.author.edit', compact('author'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Author $author)
    {
        $request->validate([
            'name' => 'required',
            'proffession_en' => 'required',
            'proffession_de' => 'required',
        ]);

        $photo = $author->photo;

        if ($request->photo) {
            $request->validate([
                'photo' => 'required|mimes:jpg,jpeg|dimensions:min_width=512,min_height=512',
            ]);

            $photo = $this->upload($request->photo, true, $photo);
        }

        $author->update([
            'photo' => $photo,
            'name' => $request->name,
            'proffession_en' => $request->proffession_en,
            'proffession_de' => $request->proffession_de,
        ]);

        return back();
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(Request $request, Author $author)
    {
        $author->delete();
        if ($request->ajax()) return response()->json(['success' => true], 200);
        return redirect()->route('author.index');
    }
}

resources/views/admin/author/create.blade.php
@extends('layouts.admin')

@section('content')
  <form action="{{route('author.store')}}" method="post" enctype="multipart/form-data">
  @csrf

    <!-- Photo -->
    <div class="form-group row">
      <label for="input" class="col-sm-2 col-form-label text-uppercase">Photo</label>

      <div class="col-sm-9">
        <div class="custom-file">
          <input type="file" class="custom-file-input @error('photo') is-invalid @enderror" id="inputGroupFile01" name="photo" aria-describedby="inputGroupFileAddon01" required>
          <small class="text-muted">512X512</small>

          <label class="custom-file-label" for="inputGroupFile01">Choose file</label>

          @error('photo')
          <span class="invalid-feedback" role="alert">
            <strong>{{ $message }}</strong>
          </span>
          @enderror
        </div>
      </div>
    </div>
    <!-- End Photo -->

    <!-- Name -->
    <div class="form-group row">
      <label for="input2" class="col-sm-2 col-form-label text-uppercase">Vorname/Name</label>

      <div class="col-sm-9">
        <input type="text" id="input2" class="form-control @error('name') is-invalid @enderror" name="name" value="{{old('name')}}" required>

        @error('name')
        <span class="invalid-feedback" role="alert">
          <strong>{{ $message }}</strong>
        </span>
        @enderror
      </div>
    </div>
    <!-- End Name -->

    <!-- Profession En -->
    <div class="form-group row">
      <label for="input2" class="col-sm-2 col-form-label text-uppercase">Proffession En</label>

      <div class="col-sm-9">
        <input type="text" id="input2" class="form-control @error('proffession_en') is-invalid @enderror" name="proffession_en" value="{{old('proffession_en')}}" required>

        @error('proffession_en')
        <span class="invalid-feedback" role="alert">
          <strong>{{ $message }}</strong>
        </span>
        @enderror
      </div>
    </div>
    <!-- Profession En -->

    <!-- Profession De -->
    <div class="form-group row">
      <label for="input2" class="col-sm-2 col-form-label text-uppercase">Beruf De</label>

      <div class="col-sm-9">
        <input type="text" id="input2" class="form-control @error('proffession_de') is-invalid @enderror" name="proffession_de" value="{{old('proffession_de')}}" required>

        @error('proffession_de')
        <span class="invalid-feedback" role="alert">
          <strong>{{ $message }}</strong>
        </span>
        @enderror
      </div>
    </div>
    <!-- End Profession De -->

    <!-- Button -->
    <div class="form-group row mt-5">
      <div class="col-sm-7">
        <button type="submit" class="btn btn-danger btn-block text-left">EINTRAG SPEICHERN</button>
      </div>
    </div>
    <!-- End Button -->
  </form>
@endsection

resources/views/admin/author/edit.blade.php
@extends('layouts.admin')

@section('content')
  <div class="row">
    <div class="col-sm-11">
      <img class="mb-4" src="{{asset($author->photo)}}" width="128px" height="128px" alt="Image Description">
    </div>
  </div>

  <form action="{{route('author.update', $author->id)}}" method="post" enctype="multipart/form-data">
    @csrf

    @method('put')

    <!-- Photo -->
    <div class="form-group row">
      <label for="input" class="col-sm-2 col-form-label text-uppercase">Photo</label>

      <div class="col-sm-9">
        <div class="custom-file">
          <input type="file" class="custom-file-input @error('photo') is-invalid @enderror" id="inputGroupFile01" name="photo" aria-describedby="inputGroupFileAddon01">
          <small class="text-muted">512X512</small>

          <label class="custom-file-label" for="inputGroupFile01">Choose file</label>

          @error('photo')
          <span class="invalid-feedback" role="alert">
            <strong>{{ $message }}</strong>
          </span>
          @enderror
        </div>
      </div>
    </div>
    <!-- End Photo -->

    <!-- Name -->
    <div class="form-group row">
      <label for="input2" class="col-sm-2 col-form-label text-uppercase">Vorname/Name</label>

      <div class="col-sm-9">
        <input type="text" id="input2" class="form-control @error('name') is-invalid @enderror" name="name" value="{{old('name') ? old('name') : $author->name}}" required>

        @error('name')
        <span class="invalid-feedback" role="alert">
          <strong>{{ $message }}</strong>
        </span>
        @enderror
      </div>
    </div>
    <!-- End Name -->

    <!-- Profession En -->
    <div class="form-group row">
      <label for="input2" class="col-sm-2 col-form-label text-uppercase">Proffession En</label>

      <div class="col-sm-9">
        <input type="text" id="input2" class="form-control @error('proffession_en') is-invalid @enderror" name="proffession_en" value="{{old('proffession_en') ? old('proffession_en') : $author->proffession_en}}" required>

        @error('proffession_en')
        <span class="invalid-feedback" role="alert">
          <strong>{{ $message }}</strong>
        </span>
        @enderror
      </div>
    </div>
    <!-- Profession En -->

    <!-- Profession De -->
    <div class="form-group row">
      <label for="input2" class="col-sm-2 col-form-label text-uppercase">Beruf De</label>

      <div class="col-sm-9">
        <input type="text" id="input2" class="form-control @error('proffession_de') is-invalid @enderror" name="proffession_de" value="{{old('proffession_de') ? old('proffession_de') : $author->proffession_de}}" required>

        @error('proffession_de')
        <span class="invalid-feedback" role="alert">
          <strong>{{ $message }}</strong>
        </span>
        @enderror
      </div>
    </div>
    <!-- End Profession De -->

    <!-- Button -->
    <div class="form-group row mt-5">
      <div class="col-sm-7">
        <div class="d-flex">
          <button type="submit" class="btn btn-danger btn-block text-left mr-2">EINTRAG SPEICHERN</button>

          <button class="btn btn-danger" form="deleteForm">
            <img src="{{asset('img/icons/ebene.png')}}" alt="Image Description">
          </button>
        </div>
      </div>
    </div>
    <!-- End Button -->
  </form>

  <form id="deleteForm" action="{{route('author.destroy', $author->id)}}" method="post">
    @csrf
    @method('delete')
  </form>
@endsection

resources/views/admin/author/index.blade.php
@extends('layouts.admin')

@section('content')
<form id="filterForm" action="" class="mb-4">
  <div class="row">
    <div class="col-sm-3 offset-sm-9">
      <div class="input-group">
        <input type="text" class="form-control" placeholder="Suche" name="vorname" aria-label="Recipient's username"
          aria-describedby="button-addon2">
        <div class="input-group-append">
          <button class="btn btn-secondary" type="submit" id="button-addon2">&#8594;</button>
        </div>
      </div>
    </div>
  </div>
</form>

<div class="table-responsive">
  <table class="table">
    <thead class="thead-light">
      <tr>
        <th class="text-uppercase" scope="col">Id</th>
        <th scope="col">Photo</th>
        <th scope="col">Vorname</th>
        <th scope="col">Proffession</th>
        <th class="text-center text-uppercase" scope="col">BEARBEITEN</th>
        <th class="text-center text-uppercase" scope="col">Löschen</th>
      </tr>
    </thead>
    <tbody>
      @foreach($authors as $author)
      <tr>
        <td>{{$author->id}}</td>
        <td>
          <img class="img-fluid rounded-circle" width="40px" src="{{asset($author->photo)}}" alt="{{$author->name}}">
        </td>
        <td>{{$author->name}}</td>
        <td>{{$author->proffession_de}}</td>
        <td class="text-center">
          <a href="{{route('author.edit', $author->id)}}">
            <img src="{{asset('img/icons/edit.png')}}" alt="Image Description">
          </a>
        </td>
        <td class="text-center">
          <a href="#" class="delete" data-id="{{ $author->id }}" data-slug="author" data-toggle="modal"
            data-target="#deleteModal">
            <img src="{{asset('img/icons/delete.png')}}" alt="Image Description">
          </a>
        </td>
      </tr>
      @endforeach
    </tbody>
  </table>
</div>

<div class="row">
  <div class="col-sm-3 mb-3 mb-sm-3">
    <a class="btn btn-danger btn-block text-left" href="{{route('author.create')}}">EINTRAG ERFASSEN</a>
  </div>

  <div class="col-sm-9">
    {{$authors->links()}}
  </div>
</div>
@endsection