routes/web.php
<?php

use App\Imports\ServicesImport;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes([
    'register' => false,
    'reset' => false,
    'verify' => false
]);

Route::group(['middleware' => 'role:admin'], function () {
    Route::resource('place', 'PlaceController')->except('show');
    Route::resource('event', 'EventController')->except('show');
    Route::resource('email-banner', 'EmailBannerController')->except('show');
    Route::resource('tip', 'TipController')->except('show');
    Route::resource('service', 'ServiceController')->except('show');
    Route::resource('shop', 'ShopController')->except('show');
    Route::resource('ad', 'AdvertisingController')->except('show');
    Route::resource('user', 'UserController')->except('show');
    Route::resource('author', 'AuthorController')->except('show');
    Route::get('logout', 'Auth\AuthController@logout')->name('logout');


    Route::get('diactivate/place/{place}', 'PlaceController@diactivate')->name('place.diactivate');
    Route::get('diactivate/email-banner/{emailBanner}', 'EmailBannerController@diactivate')->name('email-banner.diactivate');
    Route::get('diactivate/event/{event}', 'EventController@diactivate')->name('event.diactivate');
    Route::get('diactivate/tip/{tip}', 'TipController@diactivate')->name('tip.diactivate');
    Route::get('diactivate/service/{service}', 'ServiceController@diactivate')->name('service.diactivate');
    Route::get('diactivate/shop/{shop}', 'ShopController@diactivate')->name('shop.diactivate');
    Route::get('diactivate/ad/{ad}', 'AdvertisingController@diactivate')->name('ad.diactivate');

    // Excel export
    Route::get('user/export', 'UserController@export')->name('user.export');
    Route::get('/excel-imports', function () {
        return view('import');
    });

    Route::post('import-data', function (Request $request) {
        Excel::import(new ServicesImport, $request->file('file'));
        return back();
    })->name('import');
});

Route::get('password/reset', 'Auth\AuthController@resetPassword')->name('reset.password');
Route::post('password/update', 'Auth\AuthController@updatePassword')->name('update.password');
Route::get('account/activate', 'Auth\AuthController@accountActivate')->name('activate.account');
Route::get('redirect/{token}', 'RedirectController@index')->name('redirect');
Route::get('/welcome', 'RedirectController@index');

Route::get('/bucket-list/{token}', 'UserController@bucketMap')->name('bucket.list');


Route::get('/welcome', function () {
    return view('welcome');
});

Route::get('home', function () {
    return view('home');
});

Route::get('/', function () {
    return redirect()->route('login');
});


Route::get('fake/users', function () {
    factory(App\User::class, 100)->create();
});

resources/views/admin/ad/create.blade.php
@extends('layouts.admin')

@section('content')
  <form action="{{route('ad.store')}}" method="post" enctype="multipart/form-data">
  @csrf

    <!-- Preview -->
    <div class="form-group row">
      <label for="input" class="col-sm-2 col-form-label text-uppercase">Photo preview</label>

      <div class="col-sm-9">
        <div class="custom-file">
          <input type="file" class="custom-file-input @error('preview') is-invalid @enderror" id="inputGroupFile01" name="preview" aria-describedby="inputGroupFileAddon01" required>
          <small class="text-muted">1120X780</small>

          <label class="custom-file-label" for="inputGroupFile01">Choose file</label>

          @error('preview')
          <span class="invalid-feedback" role="alert"> <strong>{{ $message }}</strong> </span>
          @enderror
        </div>
      </div>
    </div>
    <!-- End Preview -->

    <!-- Firma -->
    <div class="form-group row">
      <label for="input2" class="col-sm-2 col-form-label text-uppercase">Firma</label>

      <div class="col-sm-9">
        <input type="text" id="input2" class="form-control @error('firma') is-invalid @enderror" name="firma" value="{{old('firma')}}" required>

        @error('firma')
        <span class="invalid-feedback" role="alert"> <strong>{{ $message }}</strong> </span>
        @enderror
      </div>
    </div>
    <!-- End Firma -->

    <!-- Weblink -->
    <div class="form-group row">
      <label for="input9" class="col-sm-2 col-form-label text-uppercase">Weblink</label>

      <div class="col-sm-9">
        <input type="url" id="input9" class="form-control @error('weblink') is-invalid @enderror" name="weblink" value="{{old('weblink')}}">

        @error('weblink')
        <span class="invalid-feedback" role="alert"> <strong>{{ $message }}</strong> </span>
        @enderror
      </div>
    </div>
    <!-- End Weblink -->

    <!-- Rubrik -->
    <div class="form-group row">
      <label for="input6" class="col-sm-2 col-form-label text-uppercase">Rubrik</label>

      <div class="col-sm-9">
        <select id="input6" class="custom-select @error('topic_id') is-invalid @enderror" name="topic_id" required>
          <option value=""></option>
          @foreach($categories as $category)
            <option value="{{$category->id}}" @if(old('topic_id') == $category->id) selected @endif>{{$category->name_de}}</option>
          @endforeach
        </select>

        @error('topic_id')
        <span class="invalid-feedback" role="alert"> <strong>{{ $message }}</strong> </span>
        @enderror
      </div>
    </div>
    <!-- End Rubrik -->

    <!-- Date -->
    <div class="form-group row">
      <label class="col-sm-2 col-form-label text-uppercase">Gültig</label>

      <div class="col-sm-4">
        <input type="date" class="form-control @error('valid_from') is-invalid @enderror" name="valid_from" value="{{old('valid_from')}}">

        @error('valid_from')
        <span class="invalid-feedback" role="alert"> <strong>{{ $message }}</strong> </span>
        @enderror
      </div>

      <div class="col-sm-4">
        <input type="date" class="form-control @error('valid_to') is-invalid @enderror" name="valid_to" value="{{old('valid_to')}}">

        @error('valid_to')
        <span class="invalid-feedback" role="alert"> <strong>{{ $message }}</strong> </span>
        @enderror
      </div>
    </div>
    <!-- End Date -->

    <!-- Button -->
    <div class="form-group row mt-5">
      <div class="col-sm-7">
        <button type="submit" class="btn btn-danger btn-block text-left">EINTRAG SPEICHERN</button>
      </div>
    </div>
    <!-- End Button -->
  </form>
@endsection

resources/views/admin/ad/edit.blade.php
@extends('layouts.admin')

@section('content')
<div class="row">
    <div class="col-sm-11">
        <img class="img-fluid mb-4" src="{{asset($ad->preview)}}" width="336px" height="234px" alt="Image Description">
    </div>
</div>

<form action="{{route('ad.update', $ad->id)}}" method="post" enctype="multipart/form-data">
    @csrf

    @method('put')

    <!-- Preview -->
    <div class="form-group row">
        <label for="input" class="col-sm-2 col-form-label text-uppercase">Photo preview</label>

        <div class="col-sm-9">
            <div class="custom-file">
                <input type="file" class="custom-file-input @error('preview') is-invalid @enderror"
                    id="inputGroupFile01" name="preview" aria-describedby="inputGroupFileAddon01">
                <small class="text-muted">1120X780</small>

                <label class="custom-file-label" for="inputGroupFile01">Choose file</label>

                @error('preview')
                <span class="invalid-feedback" role="alert"> <strong>{{ $message }}</strong> </span>
                @enderror
            </div>
        </div>
    </div>
    <!-- End Preview -->

    <!-- Firma -->
    <div class="form-group row">
        <label for="input2" class="col-sm-2 col-form-label text-uppercase">Firma</label>

        <div class="col-sm-9">
            <input type="text" id="input2" class="form-control @error('firma') is-invalid @enderror" name="firma"
                value="{{old('firma') ? old('firma') : $ad->firma}}" required>

            @error('firma')
            <span class="invalid-feedback" role="alert"> <strong>{{ $message }}</strong> </span>
            @enderror
        </div>
    </div>
    <!-- End Firma -->

    <!-- Weblink -->
    <div class="form-group row">
        <label for="input9" class="col-sm-2 col-form-label text-uppercase">Weblink</label>

        <div class="col-sm-9">
            <input type="url" id="input9" class="form-control @error('weblink') is-invalid @enderror" name="weblink"
                value="{{old('weblink') ? old('weblink') : $ad->weblink}}">

            @error('weblink')
            <span class="invalid-feedback" role="alert"> <strong>{{ $message }}</strong> </span>
            @enderror
        </div>
    </div>
    <!-- End Weblink -->

    <!-- Rubrik -->
    <div class="form-group row">
        <label for="input6" class="col-sm-2 col-form-label text-uppercase">Rubrik</label>

        <div class="col-sm-9">
            <select id="input6" class="custom-select @error('topic_id') is-invalid @enderror" name="topic_id" required>
                <option value=""></option>
                @foreach($categories as $category)
                <option value="{{$category->id}}" @if($ad->topic_id == $category->id) selected
                    @endif>{{$category->name_de}}</option>
                @endforeach
            </select>

            @error('topic_id')
            <span class="invalid-feedback" role="alert"> <strong>{{ $message }}</strong> </span>
            @enderror
        </div>
    </div>
    <!-- End Rubrik -->

    <!-- Date -->
    <div class="form-group row">
        <label class="col-sm-2 col-form-label text-uppercase">Gültig</label>

        <div class="col-sm-4">
            <input type="date" class="form-control @error('valid_from') is-invalid @enderror" name="valid_from"
                value="{{old('valid_from') ? old('valid_from') : $ad->valid_from}}">

            @error('valid_from')
            <span class="invalid-feedback" role="alert"> <strong>{{ $message }}</strong> </span>
            @enderror
        </div>

        <div class="col-sm-4">
            <input type="date" class="form-control @error('valid_to') is-invalid @enderror" name="valid_to"
                value="{{old('valid_to') ? old('valid_to') : $ad->valid_to}}">

            @error('valid_to')
            <span class="invalid-feedback" role="alert"> <strong>{{ $message }}</strong> </span>
            @enderror
        </div>
    </div>
    <!-- End Date -->

    <!-- Button -->
    <div class="form-group row mt-5">
        <div class="col-sm-7">
            <div class="d-flex">
                <button type="submit" class="btn btn-danger btn-block text-left mr-2">EINTRAG SPEICHERN</button>

                <button class="btn btn-danger" form="deleteForm">
                    <img src="{{asset('img/icons/ebene.png')}}" alt="Image Description">
                </button>
            </div>
        </div>
    </div>
    <!-- End Button -->
</form>

<form id="deleteForm" action="{{route('ad.destroy', $ad->id)}}" method="post">
    @csrf
    @method('delete')
</form>
@endsection

resources/views/admin/ad/index.blade.php
@extends('layouts.admin')

@section('content')
<form id="filterForm" action="" class="mb-4">
  <div class="row">
    <div class="col-sm-3 offset-sm-6 mb-3 mb-sm-0">
      <select id="categoriesFilter" class="custom-select" name="ad_topic">
        <option value="">All Kategorie</option>
        @foreach($categories as $category)
        <option value="{{$category->id}}" @if(request()->topic == $category->id) selected @endif>{{$category->name_de}}
        </option>
        @endforeach
      </select>
    </div>
    <div class="col-sm-3">
      <div class="input-group">
        <input type="text" class="form-control" placeholder="Suche" name="firma" aria-label="Recipient's username"
          aria-describedby="button-addon2">
        <div class="input-group-append">
          <button class="btn btn-secondary" type="submit" id="button-addon2">&#8594;</button>
        </div>
      </div>
    </div>
  </div>
</form>

<div class="table-responsive">
  <table class="table">
    <thead class="thead-light">
      <tr>
        <th class="text-uppercase" scope="col">Id</th>
        <th scope="col">Firma</th>
        <th scope="col">Kategorie</th>
        <th scope="col">Aktiv bis</th>
        <th scope="col">Anzahl Views</th>
        <th scope="col">Anzahl Webklicks</th>
        <th scope="col">Status</th>
        <th class="text-center text-uppercase" scope="col">BEARBEITEN</th>
        <th class="text-center text-uppercase" scope="col">Löschen</th>

      </tr>
    </thead>
    <tbody>
      @foreach($ads as $ad)
      <tr>
        <td>{{$ad->id}}</td>
        <td>{{$ad->firma}}</td>
        <td>{{$ad->topic->name_de}}</td>
        <td>{{$ad->valid_to}}</td>
        <td>{{$ad->getActivityCount('detail')}}</td>
        <td>{{$ad->getActivityCount('weblink')}}</td>
        <td>
          <a href="{{route('ad.diactivate', $ad->id)}}">
            <img src="{{asset('img/icons/status-' . $ad->status . '.png')}}" alt="Image Description">
          </a>
        </td>
        <td class="text-center">
          <a href="{{route('ad.edit', $ad->id)}}">
            <img src="{{asset('img/icons/edit.png')}}" alt="Image Description">
          </a>
        </td>
        <td class="text-center">
          <a href="#" class="delete" data-id="{{ $ad->id }}" data-slug="ad" data-toggle="modal"
            data-target="#deleteModal">
            <img src="{{asset('img/icons/delete.png')}}" alt="Image Description">
          </a>
        </td>
      </tr>
      @endforeach
    </tbody>
  </table>
</div>

<div class="row">
  <div class="col-sm-3 mb-3 mb-sm-3">
    <a class="btn btn-danger btn-block text-left" href="{{route('ad.create')}}">EINTRAG ERFASSEN</a>
  </div>

  <div class="col-sm-9">
    {{$ads->links()}}
  </div>
</div>
@endsection