routes/web.php
<?php

use App\Imports\ServicesImport;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes([
    'register' => false,
    'reset' => false,
    'verify' => false
]);

Route::group(['middleware' => 'role:admin'], function () {
    Route::resource('place', 'PlaceController')->except('show');
    Route::resource('event', 'EventController')->except('show');
    Route::resource('email-banner', 'EmailBannerController')->except('show');
    Route::resource('tip', 'TipController')->except('show');
    Route::resource('service', 'ServiceController')->except('show');
    Route::resource('shop', 'ShopController')->except('show');
    Route::resource('ad', 'AdvertisingController')->except('show');
    Route::resource('user', 'UserController')->except('show');
    Route::resource('author', 'AuthorController')->except('show');
    Route::get('logout', 'Auth\AuthController@logout')->name('logout');


    Route::get('diactivate/place/{place}', 'PlaceController@diactivate')->name('place.diactivate');
    Route::get('diactivate/email-banner/{emailBanner}', 'EmailBannerController@diactivate')->name('email-banner.diactivate');
    Route::get('diactivate/event/{event}', 'EventController@diactivate')->name('event.diactivate');
    Route::get('diactivate/tip/{tip}', 'TipController@diactivate')->name('tip.diactivate');
    Route::get('diactivate/service/{service}', 'ServiceController@diactivate')->name('service.diactivate');
    Route::get('diactivate/shop/{shop}', 'ShopController@diactivate')->name('shop.diactivate');
    Route::get('diactivate/ad/{ad}', 'AdvertisingController@diactivate')->name('ad.diactivate');

    // Excel export
    Route::get('user/export', 'UserController@export')->name('user.export');
    Route::get('/excel-imports', function () {
        return view('import');
    });

    Route::post('import-data', function (Request $request) {
        Excel::import(new ServicesImport, $request->file('file'));
        return back();
    })->name('import');
});

Route::get('password/reset', 'Auth\AuthController@resetPassword')->name('reset.password');
Route::post('password/update', 'Auth\AuthController@updatePassword')->name('update.password');
Route::get('account/activate', 'Auth\AuthController@accountActivate')->name('activate.account');
Route::get('redirect/{token}', 'RedirectController@index')->name('redirect');
Route::get('/welcome', 'RedirectController@index');

Route::get('/bucket-list/{token}', 'UserController@bucketMap')->name('bucket.list');


Route::get('/welcome', function () {
    return view('welcome');
});

Route::get('home', function () {
    return view('home');
});

Route::get('/', function () {
    return redirect()->route('login');
});


Route::get('fake/users', function () {
    factory(App\User::class, 100)->create();
});

resources/views/layouts/admin.blade.php
<!doctype html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}" defer></script>

    <!-- Fonts -->
    <link rel="dns-prefetch" href="//fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet">

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">

    <!-- Theme Styles -->
    <link href="{{ asset('css/theme.css') }}" rel="stylesheet">
</head>

<body>
    @include('layouts.loader')
    <div class="row no-gutters">
        <div class="col-md-2">
            @include('partials.admin-sidebar')
        </div>

        <div class="col-md-10">
            <div id="app">
                <nav class="navbar navbar-expand-md navbar-light bg-white shadow-sm d-block d-md-none">
                    <div class="container">
                        <a class="navbar-brand d-sm-none" href="{{ url('/') }}">
                            {{ config('app.name', 'Switzerland') }}
                        </a>

                        <button class="navbar-toggler" type="button" data-toggle="collapse"
                            data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent"
                            aria-expanded="false" aria-label="{{ __('Toggle navigation') }}">
                            <span class="navbar-toggler-icon"></span>
                        </button>

                        <div class="collapse navbar-collapse" id="navbarSupportedContent">
                            <ul class="navbar-nav mr-auto">
                                <li class="nav-item">
                                    <a class="nav-link" href="#"
                                        onclick="event.preventDefault();document.getElementById('logout-form').submit();">Abmelden</a>
                                    <form id="logout-form" action="{{ route('logout') }}" method="POST"
                                        style="display: none;">
                                        @csrf
                                    </form>
                                </li>
                                <li class="nav-item" data-name='author'>
                                    <a class="nav-link" href="{{route('author.index')}}">Authors</a>
                                </li>
                                <li class="nav-item" data-name='place'>
                                    <a class="nav-link" href="{{route('place.index')}}">Must see
                                        {{request()->is(route('place.index'))}}</a>
                                </li>
                                <li class="nav-item" data-name='event'>
                                    <a class="nav-link" href="{{route('event.index')}}">Events & Tickets</a>
                                </li>
                                <li class="nav-item" data-name='tip'>
                                    <a class="nav-link" href="{{route('tip.index')}}">Tips from Locals</a>
                                </li>
                                <li class="nav-item" data-name='service'>
                                    <a class="nav-link" href="{{route('service.index')}}">Services</a>
                                </li>
                                <li class="nav-item" data-name='shop'>
                                    <a class="nav-link" href="{{route('shop.index')}}">Souvenir Shop</a>
                                </li>
                                <li class="nav-item" data-name='user'>
                                    <a class="nav-link" href="{{route('user.index')}}">Bucket list users</a>
                                </li>
                                <li class="nav-item " data-name='ad'>
                                    <a class="nav-link" href="{{route('ad.index')}}">Advertising banner</a>
                                </li>
                                <li class="nav-item " data-name='email-banner'>
                                    <a class="nav-link" href="{{route('email-banner.index')}}">Email banner</a>
                                </li>
                            </ul>
                        </div>
                    </div>
                </nav>

                <main class="admin-content">
                    <div class="container py-5">
                        @yield('content')
                    </div>
                    <!-- Modal -->
                    <div class="modal fade" id="deleteModal" tabindex="-1" role="dialog" aria-hidden="true">
                        <div class="modal-dialog modal-dialog-centered" role="document">
                            <div class="modal-content">
                                <div class="modal-header">
                                    <h5 class="modal-title" id="exampleModalLongTitle">
                                    </h5>
                                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                        <span aria-hidden="true">&times;</span>
                                    </button>
                                </div>
                                <div class="modal-body">
                                    Möchten Sie dies wirklich löschen?
                                </div>
                                <div class="modal-footer">
                                    <button type="button" class="btn btn-secondary"
                                        data-dismiss="modal">Schließen</button>
                                    <button type="button" class="delete-item btn btn-danger">Löschen</button>
                                </div>
                            </div>
                        </div>
                    </div>
                </main>
            </div>
        </div>
    </div>

    <script src="{{ asset('js/jquery-3.4.1.min.js') }}"></script>
    <script src="https://cdn.jsdelivr.net/npm/bs-custom-file-input/dist/bs-custom-file-input.min.js"></script>
    <script type="text/javascript">
        document.body.style.setProperty('overflow','hidden')
        $(document).ready(function () {
            setTimeout(() => {
                $('.loader').addClass('disactive')
                document.body.style.removeProperty('overflow');
            }, 1000);
        });
    </script>
    <script>
        $(document).on('click', '.delete-item', function(e){
            $('.loader').removeClass('disactive')
            let id = e.currentTarget.dataset.id;
            let route = e.currentTarget.dataset.route + '/' + id;
            let method = 'delete';
            let csrf ='{{ csrf_token() }}';
            $.ajax({
                type: method,
                url: route,
                data: {'_token': csrf},
                dataType: "json",
                success: function (response) {
                    location.reload();
                },
                error:function(xhr){
                    location.reload();
                }
            });
        });
                
        let showPopup = function (id,route,method = 'delete') {  
            let btn = document.querySelector('.delete-item');
            btn.dataset.id = id;
            btn.dataset.route = route;
            $('#deleteModal .modal-title').html(`Artikel  <b>#${id}</b>`);
        }

    </script>
    <script>
        $(document).ready(function () {
        bsCustomFileInput.init()

        $('#categoriesFilter').on('change', function () {
            // debugger;
          document.forms['filterForm'].submit();
        });
        $('#regionsFilter').on('change', function () {
          document.forms['filterForm'].submit();
        });
        let url = window.location.href.split("/")[3];
        url = url.split('?')[0];
        $('.nav-item[data-name='+url+']').addClass('active')
        $('.delete').click(function (e) { 
        let id = e.currentTarget.dataset.id;
        let route = e.currentTarget.dataset.slug;
        showPopup(id,route);
        });

      })
    </script>
    @yield('javascript')
</body>

</html>

resources/views/layouts/app.blade.php
<!doctype html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}" defer></script>

    <!-- Fonts -->
    <link rel="dns-prefetch" href="//fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet">

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
</head>

<body>
    <div id="app">

        <nav class="navbar navbar-expand-md navbar-light bg-white shadow-sm">
            <div class="container">
                <a class="navbar-brand" href="{{ isset($hide_nav) ? "#" : url('/') }}">
                    Switzerland
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse"
                    data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false"
                    aria-label="{{ __('Toggle navigation') }}">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <!-- Left Side Of Navbar -->
                    <ul class="navbar-nav mr-auto">

                    </ul>

                    <!-- Right Side Of Navbar -->
                    <ul class="navbar-nav ml-auto">
                        <!-- Authentication Links -->
                        @guest
                        @if (!isset($hide_nav))
                        <li class="nav-item">
                            <a class="nav-link" href="{{ route('login') }}">{{ __('Login') }}</a>
                        </li>
                        @endif
                        @if (Route::has('register'))
                        <li class="nav-item">
                            <a class="nav-link" href="{{ route('register') }}">{{ __('Register') }}</a>
                        </li>
                        @endif
                        @else
                        <li class="nav-item dropdown">
                            <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button"
                                data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                                {{ Auth::user()->name }} <span class="caret"></span>
                            </a>

                            <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                                <a class="dropdown-item" href="{{ route('logout') }}" onclick="event.preventDefault();
                                                             document.getElementById('logout-form').submit();">
                                    {{ __('Logout') }}
                                </a>

                                <form id="logout-form" action="{{ route('logout') }}" method="POST"
                                    style="display: none;">
                                    @csrf
                                </form>
                            </div>
                        </li>
                        @endguest
                    </ul>
                </div>
            </div>
        </nav>
        <main class="py-4">
            @yield('content')
        </main>
    </div>
</body>

</html>

resources/views/layouts/bucket_map.blade.php
<!doctype html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}" defer></script>

    <!-- Fonts -->
    <link rel="dns-prefetch" href="//fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet">

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
    <link href="{{ asset('css/leaflet.css') }}" rel="stylesheet">
</head>

<body>
    <div class="container-fluid h-100">
        <div class="row h-100">
            <div class="map px-0 col-md-9">
                <div class="toggler">
                    <img src="{{ asset('img/icons/toggler.svg') }}" alt="">
                </div>
                @yield('content')
            </div>
            <div class="map-navbar col-md-3">
                <div class="d-flex py-4 align-items-center justify-content-start">
                    <img src="{{ asset('img/logo/logo.png') }}" alt="">
                </div>
                <div class="info mb-5">
                    <h5>MY BUCKET LIST</h5>
                </div>
                <ul>
                    @php
                    $index = 0
                    @endphp
                    @foreach ($data->geo_info as $slug => $item)
                    @php
                    $index++
                    @endphp
                    <li class="title">{{ $slug }}</li>
                    @foreach ($item as $key => $info)
                    <li data-guid="{{ $slug.'_'.$info->id }}"
                        class="{{ $index == 1 && $key == 0 ?'active' : '' }} link">{{ $info->title }}</li>
                    @endforeach

                    @endforeach
                </ul>
            </div>
        </div>
    </div>

    <style>
        .map {}

        .map-navbar {
            background-color: #2e2825;
            overflow-y: auto;
            height: 100%;
            transition: all .3s linear;
        }

        .map-navbar ul {
            margin: 0;
            padding: 0;
            list-style: none;
            color: #fff;
        }

        .map-navbar ul .title {
            text-transform: uppercase;
            font-weight: bold;
            margin: 8px 0;
            padding: 2px;
            font-size: 20px;
            border-bottom: 2px solid #fff;
            position: relative;
        }

        /* .map-navbar ul .title::before {
            content: '';
            width: 100%;
            height: 2px;
            background: #c6001e;
            position: absolute;
            left: 0;
            bottom: -4px;
        } */

        .info {
            text-align: left;
            color: #fff;
        }

        .info h5 {
            font-size: 20px;
            font-weight: bold;
        }

        .map-navbar ul .link {
            cursor: pointer;
            padding: 4px;
            transition: all .3s linear;
        }

        .active {
            color: #c6001e;
        }

        .map-navbar ul .link:hover {
            color: #c6001e;
        }

        /* @media only screen and (max-width: 600px) {
            body {
                background-color: lightblue;
            }
        } */
        .navbar-active {
            right: 0 !important;
            display: block !important;
        }

        .toggler {
            cursor: pointer;
            position: fixed;
            top: 20px;
            right: 20px;
            z-index: 111111;
            padding: 10px;
            background: #fff;
            border-radius: 5px;
            background: #e3342f;
            box-shadow: 0px 2px 9px 0px #000000db;
            display: none;
        }

        .toggler-diactive {
            display: none !important;
        }

        @media(max-width:768px) {
            .toggler {
                display: block;
            }

            .map-navbar {
                position: absolute;
                display: none;
                right: -100%;
                top: 0;
                width: 100%;
                height: 100%;
                z-index: 111111;
                background-color: #2e2825d9;
            }
        }
    </style>

    <script src="{{ asset('js/jquery-3.4.1.min.js') }}"></script>
    <script src="{{ asset('js/leaflet.js') }}"></script>
    <script src="https://cdn.jsdelivr.net/npm/bs-custom-file-input/dist/bs-custom-file-input.min.js"></script>
    @yield('javascript')
</body>

</html>

resources/views/layouts/loader.blade.php
<div class="loader">
    <div class="lds-roller">
        <div></div>
        <div></div>
        <div></div>
        <div></div>
        <div></div>
        <div></div>
        <div></div>
        <div></div>
    </div>
</div>
<style>
    .loader {
        display: flex;
        align-items: center;
        justify-content: center;
        position: fixed;
        z-index: 99999999;
        width: 100%;
        height: 100vh;
        top: 0;
        left: 0%;
        background-color: #fff;
    }

    .disactive {
        display: none;
    }

    .lds-roller {
        display: inline-block;
        position: relative;
        width: 80px;
        height: 80px;
    }

    .lds-roller div {
        animation: lds-roller 1.2s cubic-bezier(0.5, 0, 0.5, 1) infinite;
        transform-origin: 40px 40px;
    }

    .lds-roller div:after {
        content: " ";
        display: block;
        position: absolute;
        width: 7px;
        height: 7px;
        border-radius: 50%;
        background: #c6001e;
        margin: -4px 0 0 -4px;
    }

    .lds-roller div:nth-child(1) {
        animation-delay: -0.036s;
    }

    .lds-roller div:nth-child(1):after {
        top: 63px;
        left: 63px;
    }

    .lds-roller div:nth-child(2) {
        animation-delay: -0.072s;
    }

    .lds-roller div:nth-child(2):after {
        top: 68px;
        left: 56px;
    }

    .lds-roller div:nth-child(3) {
        animation-delay: -0.108s;
    }

    .lds-roller div:nth-child(3):after {
        top: 71px;
        left: 48px;
    }

    .lds-roller div:nth-child(4) {
        animation-delay: -0.144s;
    }

    .lds-roller div:nth-child(4):after {
        top: 72px;
        left: 40px;
    }

    .lds-roller div:nth-child(5) {
        animation-delay: -0.18s;
    }

    .lds-roller div:nth-child(5):after {
        top: 71px;
        left: 32px;
    }

    .lds-roller div:nth-child(6) {
        animation-delay: -0.216s;
    }

    .lds-roller div:nth-child(6):after {
        top: 68px;
        left: 24px;
    }

    .lds-roller div:nth-child(7) {
        animation-delay: -0.252s;
    }

    .lds-roller div:nth-child(7):after {
        top: 63px;
        left: 17px;
    }

    .lds-roller div:nth-child(8) {
        animation-delay: -0.288s;
    }

    .lds-roller div:nth-child(8):after {
        top: 56px;
        left: 12px;
    }

    @keyframes lds-roller {
        0% {
            transform: rotate(0deg);
        }

        100% {
            transform: rotate(360deg);
        }
    }
</style>