routes/web.php
<?php

use App\Imports\ServicesImport;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes([
    'register' => false,
    'reset' => false,
    'verify' => false
]);

Route::group(['middleware' => 'role:admin'], function () {
    Route::resource('place', 'PlaceController')->except('show');
    Route::resource('event', 'EventController')->except('show');
    Route::resource('email-banner', 'EmailBannerController')->except('show');
    Route::resource('tip', 'TipController')->except('show');
    Route::resource('service', 'ServiceController')->except('show');
    Route::resource('shop', 'ShopController')->except('show');
    Route::resource('ad', 'AdvertisingController')->except('show');
    Route::resource('user', 'UserController')->except('show');
    Route::resource('author', 'AuthorController')->except('show');
    Route::get('logout', 'Auth\AuthController@logout')->name('logout');


    Route::get('diactivate/place/{place}', 'PlaceController@diactivate')->name('place.diactivate');
    Route::get('diactivate/email-banner/{emailBanner}', 'EmailBannerController@diactivate')->name('email-banner.diactivate');
    Route::get('diactivate/event/{event}', 'EventController@diactivate')->name('event.diactivate');
    Route::get('diactivate/tip/{tip}', 'TipController@diactivate')->name('tip.diactivate');
    Route::get('diactivate/service/{service}', 'ServiceController@diactivate')->name('service.diactivate');
    Route::get('diactivate/shop/{shop}', 'ShopController@diactivate')->name('shop.diactivate');
    Route::get('diactivate/ad/{ad}', 'AdvertisingController@diactivate')->name('ad.diactivate');

    // Excel export
    Route::get('user/export', 'UserController@export')->name('user.export');
    Route::get('/excel-imports', function () {
        return view('import');
    });

    Route::post('import-data', function (Request $request) {
        Excel::import(new ServicesImport, $request->file('file'));
        return back();
    })->name('import');
});

Route::get('password/reset', 'Auth\AuthController@resetPassword')->name('reset.password');
Route::post('password/update', 'Auth\AuthController@updatePassword')->name('update.password');
Route::get('account/activate', 'Auth\AuthController@accountActivate')->name('activate.account');
Route::get('redirect/{token}', 'RedirectController@index')->name('redirect');
Route::get('/welcome', 'RedirectController@index');

Route::get('/bucket-list/{token}', 'UserController@bucketMap')->name('bucket.list');


Route::get('/welcome', function () {
    return view('welcome');
});

Route::get('home', function () {
    return view('home');
});

Route::get('/', function () {
    return redirect()->route('login');
});


Route::get('fake/users', function () {
    factory(App\User::class, 100)->create();
});

app/User.php
<?php

namespace App;

use App\Filters\UserFilter as Filters;
use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Laravel\Sanctum\HasApiTokens;
use Spatie\Permission\Traits\HasRoles;

class User extends Authenticatable
{
    use Notifiable, HasApiTokens, HasRoles, EntryFilter;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'last_name', 'email', 'password', 'status',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

    protected static function booted()
    {
        parent::booted(); // TODO: Change the autogenerated stub

        static::deleting(function ($model) {
            $model->bucket->each->delete();
        });
    }

    /**
     * Get user all bucket list.
     *
     * @return \Illuminate\Database\Eloquent\Relations\HasMany
     */
    public function bucket()
    {
        return $this->hasMany(Bucket::class);
    }

    /**
     * Apply all relevant user filters.
     *
     * @param  Builder $query
     * @param \App\Filters\UserFilter $filters
     * @return Builder
     */
    public function scopeFilter($query, Filters $filters)
    {
        return $filters->apply($query);
    }
}

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use App\BucketImport;
use App\Exports\UsersExport;
use Maatwebsite\Excel\Facades\Excel;
use App\Filters\UserFilter;
use App\User;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Hash;

class UserController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(UserFilter $filters)
    {
        $users = User::latest()->filter($filters)->with('bucket')->paginate(25);

        return view('admin.user.index', compact('users'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  User  $id
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.user.create');
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  User  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(User $user)
    {
        return view('admin.user.edit', compact('user'));
    }

    public function store(Request $request)
    {
        $user = $request->validate([
            'last_name' => 'required|string|max:255',
            'name' => 'required|string|max:255',
            'email' => 'required|string|email|max:255|unique:users',
            'password' => 'required|string|min:8'
        ]);

        User::create($user);

        return redirect()->route('user.index');
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  User  $user
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, User $user)
    {
        $request->validate([
            'last_name' => 'required|string|max:255',
            'name' => 'required|string|max:255',
            'email' => 'required|string|email|max:255'
        ]);

        if ($request->last_name !== $user->last_name) {
            $user->last_name = $request->last_name;
        }

        if ($request->name !== $user->name) {
            $user->name = $request->name;
        }

        if ($request->email !== $user->email) {
            $request->validate([
                'email' => 'unique:users',
            ]);

            $user->email = $request->email;
        }

        if ($request->password) {
            $request->validate([
                'password' => 'required|string|min:8'
            ]);

            $user->password = Hash::make($request->password);
        }

        $user->save();

        return back();
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  User  $user
     * @return \Illuminate\Http\Response
     */
    public function destroy(Request $request, User $user)
    {
        $user->tokens()->delete();
        $user->delete();

        if ($request->ajax()) return response()->json(['success' => true], 200);

        return redirect()->route('user.index');
    }

    /**
     * Export all users to exel
     *
     * @return mixed
     */
    public function export()
    {
        return Excel::download(new UsersExport(), 'users(' . date("Y-m-d H-i-s") . ').xlsx');
    }


    public function bucketMap($token)
    {
        $data = BucketImport::findOrFail($token);
        $data->geo_info = json_decode($data->geo_info);
        return view('bucket.index')->with('data', $data);
    }
}

resources/views/admin/user/create.blade.php
@extends('layouts.admin')

@section('content')
  <form action="{{route('user.store')}}" method="post" enctype="multipart/form-data">
  @csrf
    <!-- Last Name -->
    <div class="form-group row">
      <label for="input2" class="col-sm-2 col-form-label text-uppercase">Vorname</label>

      <div class="col-sm-7">
        <input type="text" id="input2" class="form-control @error('last_name') is-invalid @enderror" name="last_name" value="{{old('last_name') ? old('last_name') : ''}}" required>

        @error('last_name')
        <span class="invalid-feedback" role="alert"> <strong>{{ $message }}</strong> </span>
        @enderror
      </div>
    </div>
    <!-- End Last Name -->

    <!-- Name -->
    <div class="form-group row">
      <label for="input-name" class="col-sm-2 col-form-label text-uppercase">Name</label>

      <div class="col-sm-7">
        <input type="text" id="input-name" class="form-control @error('name') is-invalid @enderror" name="name" value="{{old('name') ? old('name') : ''}}" required>

        @error('name')
        <span class="invalid-feedback" role="alert"> <strong>{{ $message }}</strong> </span>
        @enderror
      </div>
    </div>
    <!-- End Name -->

    <!-- Email -->
    <div class="form-group row">
      <label for="input-email" class="col-sm-2 col-form-label text-uppercase">Email</label>

      <div class="col-sm-7">
        <input type="email" id="input-email" class="form-control @error('email') is-invalid @enderror" name="email" value="{{old('email') ? old('email') : ''}}" required>

        @error('email')
        <span class="invalid-feedback" role="alert"> <strong>{{ $message }}</strong> </span>
        @enderror
      </div>
    </div>
    <!-- End Email -->

    <!-- Password -->
    <div class="form-group row">
      <label for="input-name" class="col-sm-2 col-form-label text-uppercase">Password</label>

      <div class="col-sm-7">
        <input type="password" id="input-password" class="form-control @error('password') is-invalid @enderror" name="password" required value="{{old('password')}}">

        @error('password')
        <span class="invalid-feedback" role="alert"> <strong>{{ $message }}</strong> </span>
        @enderror
      </div>
    </div>
    <!-- End Password -->

    <!-- Button -->
    <div class="form-group row mt-5">
      <div class="col-sm-7">
        <div class="d-flex">
          <button type="submit" class="btn btn-danger btn-block text-left mr-2">EINTRAG SPEICHERN</button>
        </div>
      </div>
    </div>
    <!-- End Button -->
  </form>
@endsection

resources/views/admin/user/edit.blade.php
@extends('layouts.admin')

@section('content')
  <form action="{{route('user.update', $user->id)}}" method="post" enctype="multipart/form-data">
  @csrf
  @method('put')
    <!-- Last Name -->
    <div class="form-group row">
      <label for="input2" class="col-sm-2 col-form-label text-uppercase">Vorname</label>

      <div class="col-sm-7">
        <input type="text" id="input2" class="form-control @error('last_name') is-invalid @enderror" name="last_name" value="{{old('last_name') ? old('last_name') : $user->last_name}}" required>

        @error('last_name')
        <span class="invalid-feedback" role="alert"> <strong>{{ $message }}</strong> </span>
        @enderror
      </div>
    </div>
    <!-- End Last Name -->

    <!-- Name -->
    <div class="form-group row">
      <label for="input-name" class="col-sm-2 col-form-label text-uppercase">Name</label>

      <div class="col-sm-7">
        <input type="text" id="input-name" class="form-control @error('name') is-invalid @enderror" name="name" value="{{old('name') ? old('name') : $user->name}}" required>

        @error('name')
        <span class="invalid-feedback" role="alert"> <strong>{{ $message }}</strong> </span>
        @enderror
      </div>
    </div>
    <!-- End Name -->

    <!-- Email -->
    <div class="form-group row">
      <label for="input-email" class="col-sm-2 col-form-label text-uppercase">Email</label>

      <div class="col-sm-7">
        <input type="email" id="input-email" class="form-control @error('email') is-invalid @enderror" name="email" value="{{old('email') ? old('email') : $user->email}}" required>

        @error('email')
        <span class="invalid-feedback" role="alert"> <strong>{{ $message }}</strong> </span>
        @enderror
      </div>
    </div>
    <!-- End Email -->

    <!-- Password -->
    <div class="form-group row">
      <label for="input-name" class="col-sm-2 col-form-label text-uppercase">Password</label>

      <div class="col-sm-7">
        <input type="password" id="input-password" class="form-control @error('password') is-invalid @enderror" name="password" value="{{old('password')}}">

        @error('password')
        <span class="invalid-feedback" role="alert"> <strong>{{ $message }}</strong> </span>
        @enderror
      </div>
    </div>
    <!-- End Password -->

    <!-- Button -->
    <div class="form-group row mt-5">
      <div class="col-sm-7">
        <div class="d-flex">
          <button type="submit" class="btn btn-danger btn-block text-left mr-2">EINTRAG SPEICHERN</button>

          <button class="btn btn-danger" form="deleteForm">
            <img src="{{asset('img/icons/ebene.png')}}" alt="Image Description">
          </button>
        </div>
      </div>
    </div>
    <!-- End Button -->
  </form>

  <form id="deleteForm" action="{{route('user.destroy', $user->id)}}" method="post">
    @csrf
    @method('delete')
  </form>
@endsection

resources/views/admin/user/index.blade.php
@extends('layouts.admin')

@section('content')
<form id="filterForm" action="" class="mb-4">
  <div class="row">
    <div class="col-sm-3 offset-sm-5 mb-3 mb-sm-0">
      <select id="categoriesFilter" class="custom-select" name="status">
        <option value="">All status</option>
        <option value="true" @if(request()->status === "true") selected @endif>Active</option>
        <option value="false" @if(request()->status === "false") selected @endif>Disabled</option>
      </select>
    </div>

    <div class="col-sm-3">
      <div class="input-group">
        <input type="text" class="form-control" placeholder="Suche" name="vorname" aria-label="Recipient's username"
          aria-describedby="button-addon2">
        <div class="input-group-append">
          <button class="btn btn-secondary" type="submit" id="button-addon2">&#8594;</button>
        </div>
      </div>
    </div>

    <div class="col-sm-1">
      <a class="btn btn-light" href="{{route('user.export')}}">
        <img src="{{asset('img/icons/export.png')}}" alt="Export">
      </a>
    </div>
  </div>
</form>

<div class="table-responsive">
  <table class="table">
    <thead class="thead-light">
      <tr>
        <th class="text-uppercase" scope="col">Id</th>
        <th scope="col">Vorname</th>
        <th scope="col">Name</th>
        <th scope="col">Email</th>
        <th scope="col">Register Datum</th>
        <th scope="col">Anzahl Merkliste</th>
        <th scope="col">Status</th>
        <th class="text-center text-uppercase" scope="col">BEARBEITEN</th>
        <th class="text-center text-uppercase" scope="col">Löschen</th>
      </tr>
    </thead>
    <tbody>
      @foreach($users as $user)
      <tr>
        <td>{{$user->id}}</td>
        <td>{{$user->last_name}}</td>
        <td>{{$user->name}}</td>
        <td>{{$user->email}}</td>
        <td>{{$user->created_at}}</td>
        <td>{{count($user->bucket)}}</td>
        <td>
          <img src="{{asset('img/icons/status-' . $user->status . '.png')}}" alt="Image Description">
        </td>
        <td class="text-center">
          <a href="{{route('user.edit', $user->id)}}">
            <img src="{{asset('img/icons/edit.png')}}" alt="Image Description">
          </a>
        </td>
        <td class="text-center">
          <a href="#" class="delete" data-id="{{ $user->id }}" data-slug="user" data-toggle="modal"
            data-target="#deleteModal">
            <img src="{{asset('img/icons/delete.png')}}" alt="Image Description">
          </a>
        </td>
      </tr>
      @endforeach
    </tbody>
  </table>
</div>

<div class="row">
  <div class="col-sm-3 mb-3 mb-sm-3">
    <a href="{{route('user.create')}}" class="btn btn-danger btn-block text-left">EINTRAG ERFASSEN</a>
  </div>

  <div class="col-sm-9">
    {{$users->links()}}
  </div>
</div>
@endsection